### ISSUE TITLE
Assignment 3-2 - TIY Database - Powered by Enumerable

### ISSUE THREAD

**Issue by gstark** [myk27x/assignments#10]
# Power of Enumerable

Modify last night's homework to use method from `Enumerable` other
than `each` to implement your `search` and `delete` features.

Please close this issue and include a link to your github repository. Also
close last night's homework issue and include the same link there (if you
haven't already closed that issue)

The _Adventure_ and _Epic_ modes from last night still stand.

**Comment by myk27x** [comment]
https://github.com/myk27x/database

**Comment by gstark** [comment]
Looks good except we should be using enumerables other than `#each` for searching and deleting. Come see me if you want to work on this together or if you want a hint.

**Comment by myk27x** [comment]
I plan on going back over this one. I hit such a brick wall with the finding the person.name that the rest of the assignment suffered. I will be going back to fix this.

**Comment by gstark** [comment]
Cool. Any time you go back to an assignment just comment and let me know
and I'm happy to review and give more feedback.
