### ISSUE TITLE
Assignment 3-4 - Tic-Tac-Toe

### ISSUE THREAD

**Issue by gstark** [myk27x/assignments#11]
## Explorer Mode

Make a 2 player tic-toe-toe game.
- [x] The game takes turns receiving input for each player.
- [x] The game recognizes when a player has won.
- [x] The board should be updated as it's state changes when people make moves.
- [x] If board is full before there is a winner, declare a tie.
- [x] Provide feedback for invalid moves (i.e. a player attempts to move in a space that's already filled).
### Console Interface

You should print the board state out to the console like this each time it changes:

```
 X |   | O  
--- --- ---
 X | O | X
--- --- ---
   | X | O
```

Let the player choose their move by input a number [1-9] like on a telephone pad:

```
 1 | 2 | 3  
--- --- ---
 4 | 5 | 6
--- --- ---
 7 | 8 | 9
```
## Adventure Mode

  Allow a single player to choose to play against the computer's "AI".
  Your AI might just make random moves at this point, or take a stab at making
  a smarter AI
## Epic Mode

  Your AI is unbeatable. The player will always lose or at best, tie. Yes, this is totally possible. Your game should also recognize a tie as soon as it becomes impossible to win

**Comment by myk27x** [comment]
Explorer Mode completed.

Will be making weekend attempt at personal AI.

**Comment by gstark** [comment]
Niiiiiice!!

It doesn't seem like `board.rb` is used so I suggest you `git rm` it from your repo.

Some feedback. When we see code like this:

``` ruby
  @x1x = '1'
  @x2x = '2'
  @x3x = '3'
  @x4x = '4'
  @x5x = '5'
  @x6x = '6'
  @x7x = '7'
  @x8x = '8'
  @x9x = '9'
```

we actually actually want an array. I suggest trying using an array called `@squares` and instead of saying `@x1x` you say `@squares[0]` and instead of `@x2x` you say `@squares[1]`

This should allow you to cut down the lines of code in your methods (for example: the `put_X_down` and `put_O_down` methods)

If this isn't clear, please ask on Slack.

**Comment by myk27x** [comment]
I planned on using board.rb and a few others to split into other classes but after finishing I had a harder time really validating it (esp. seeing as it's a game and not a pertinent data structure?). 

Otherwise, will be working on AI (multiple if I have time), and implementing the array suggestion. :)

**Comment by gstark** [comment]
:boom:
:+1:

**Comment by myk27x** [comment]
Adventure mode completed.
Player can choose to play against AI as either X or O.
Cleaned up code all around; specifically puts_X and puts_O.

I started to change everything in puts_X/O to @squares[i] when it finally clicked and I was able to write a function for determining choice, etc. by myself! :)

I also ran into a nasty bug where when choosing to play again there were things that didn't get reset. Took all day to re-work but finally fixed it.

**Comment by myk27x** [comment]
https://github.com/myk27x/tic-tac-toe

Added smarter AI. It's pretty sloppy, and NOW I feel like it would benefit from classes as well as some optimization/cleaning of the code (always), but it runs and meets the end result. _whew_

**Comment by gstark** [comment]
Looks good!

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/BzNXlDwnNbiCI/200w_d.gif)

**Comment by squares** [comment]
unsubscribe.
