### ISSUE TITLE
Assignment 5-2 - Databasics

### ISSUE THREAD

**Issue by gstark** [myk27x/assignments#17]
Fork the repository below and follow the instructions in the included README.md

[https://github.com/tiy-tpa-ruby-q3-2015/databasics](https://github.com/tiy-tpa-ruby-q3-2015/databasics)

**Comment by myk27x** [comment]
https://github.com/myk27x/databasics

oops on commit message; explorer completed, not adventure

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/O14RThuceJwY0/200w_d.gif)
