### ISSUE TITLE
Assignment 1-2 - User Input Statistics

### ISSUE THREAD

**Issue by gstark** [myk27x/assignments#2]
## Description

Create a program which will take repeated input from the user and generate statistics on those inputs.
## Objectives

After completing this assignment, you should...
- Understand control flow, specifically looping and branching.
- Understand variables and data types.
- Understand basic ways in which a Ruby program can present information to the user and request information from the user.
- Understand how ruby code resides on the file system.
- Be able to use `puts` and `gets`.
- Be able to perform calculations on variables.
- Be able to run ruby code from the command line.
## Deliverables
- **Ruby code.** This code should be executable, should run without errors, and should accomplish the requirements given below. Try to keep to the ruby style guide as you code.
- **A link to a Gist.** Create a Ruby Gist on http://gist.github.com and paste your Ruby code into it. Run your code in the command line. Running this with `atom-runner` or `seeing is believing` won't work for us because we are interacting with the user. Submit the link to this gist via the homework submission form found on the course website.
## Normal Mode

Your goal for tonight is to create a program to keep track of user input.  You will repeatedly ask the user to enter a number, and as long as the user types a number and hits enter, you will ask again.  If the user hits enter on a blank line (without typing a number first), this means that the user is finished.

Once the user is finished, you should present statistics about the inputs.  You should give:
- The total of all the numbers.
- The average of all the numbers.

Your program should still work if the user inputs negative numbers and/or non-integer rational numbers (e.g. `3.45`).
## Adventure Mode

Extend your program to accept strings as well.  If the user starts off by entering a string (e.g. `correct`), then the program will accept strings for subsequent inputs.  Rather than showing statistics at the end, it will show the concatenated version of the inputs.  For example, if the inputs are the following:
- `correct`
- `horse`
- `battery`
- `staple`

Then the output will be `correcthorsebatterystaple`.

Your program should continue to work exactly like Normal Mode if the user starts by entering a number.  If the user mixes numbers and strings in the same run, your program should tell the user to start over, then stop execution.
## Hard Mode

When the user is inputting numbers, add the following statistics to the output:
- Standard Deviation
- Median

When the user is inputting strings, add the following statistics to the output:
- Average length of inputs
- Number of times the letter `e` was used in the inputs.

**Comment by myk27x** [comment]
normal mode: https://gist.github.com/2d079d0bd8a4c9116286.git

adventure mode (attempts): https://gist.github.com/f5226cdb464521f7e134.git

This is where I think git would have come in very handy. In the adventure mode, at one point I was at least accepting strings and integers into my array, and lost it somewhere in the bustle of trying to check if the array had both. Would have been nice to see edits, etc. and go back to old working code to try again. (of course I started doing that onboard later with multiple saves)

**Comment by gstark** [comment]
I think these are your accurate links:

normal: https://gist.github.com/myk27x/2d079d0bd8a4c9116286
adventure: https://gist.github.com/myk27x/f5226cdb464521f7e134

_Good Stuff!!_

In your _normal_ assignment, I think your `while` loop could simply be `while num !=""` instead of the _special_ string `"l;kajgl;ijerlgknadfk"` ;) ;) ;)

**Comment by gstark** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/o7H9mn7R9SIIE/200w_d.gif)

**Comment by myk27x** [comment]
yeah, but who would have ever input `"l;kajgl;ijerlgknadfk"` lmfao

`!=` or `true` would have worked just as well, but in the moment... you know... hehehe
