### ISSUE TITLE
Assignment 1-3 - Number Guessing Game

### ISSUE THREAD

**Issue by gstark** [myk27x/assignments#3]
## Description

It is your first day at the latest Internet startup in the Valley, "nmbr."

![nmbr](http://i.imgur.com/Ngc1Olv.png)

nmbr's mission statement is:

> Bring radical transformation to the number guessing space.

In fact, the CTO just said on CNN that you are the _Uber of number guesses_. So now it is crunch mode, as nmbr's new guessing game will ship **tomorrow**!

Your task is to create a number guessing game in which the computer picks a number and users have to guess it. The computer will give you cues like 'Too High' or 'Too Low.'
## Deliverables
- [x] A GitHub repository named `nmbr`
- [x] A Ruby file in that repository called `guessing_game.rb`.
- [x] A series of commits on that repository.
- [x] When you close the assignment issue include a link to your new repository.
  
  > After you get each requirement working, run `git add .`, then `git commit -m "TEXT HERE"`, where TEXT HERE should be replaced with the description of the requirement you just finished.
  > 
  > Make sure to `git push` your changes up to GitHub.  Feel free to do this more than once along the way, of course.
## Normal Mode

Your program should:
- [x] Pick a **random** number between 1 and 100
- [x] Prompt you for a guess
- [x] If your guess is less than the program's number, it should tell you that you were low and let you guess again.
- [x] If the guess is greater than the program's number, it should tell you that you were high and let you guess again.
- [x] If your guess is correct, the program should tell you that you win and then quit.
- [x] After 5 incorrect guesses, the program should tell you that you lose.
- [x] Your code should use at least two methods.
- [x] This game should be run from the command line by typing "ruby guessing_game.rb".
## Adventure Mode

_coming soon_
## Nightmare Mode

_coming soon_

**Comment by myk27x** [comment]
https://github.com/myk27x/nmbr.git

Adv and Ntmr still read "coming soon"?

I got the text from Chad so going to see what I can make of that before I crash.

**Comment by myk27x** [comment]
Completed adventure mode with last commit.

**Comment by gstark** [comment]
Awesome stuff. I like the fancy printing output.

You've got everything here but a `class` and you are super close. If you feel like going back at some point and implementing a `class` let me know and I'll re-review. No need to, unless you want the practice.

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/2d8X4EQIdsXQc/200w_d.gif)
