### ISSUE TITLE
Assignment 9-2 - Other People's Code

### ISSUE THREAD

**Issue by gstark** [myk27x/assignments#33]
Working with other people's code is often the largest challenge a junior (or really any) developer faces. Navigating an unfamiliar code base, new gems, and even an unfamiliar coding style, can be daunting. The more we practice trying to read and understand code, the better developers we will be.
# Explorer Mode
- [x] Complete your assigned issue in the [Hours repo](https://github.com/tiy-tpa-ruby-q3-2015/Hours)
- [x] Discuss your final project idea with me to get some feedback prior to pitching them to the group
# Adventure Mode
- [x] Come up with a new improvement to the `Hours` app and create it as an issue. Request the project manager assign it to you.
- [x] Complete the implementation of this idea
# Epic Mode
- [ ] Take our code-notes from today's lecture on [Refile](https://github.com/refile/refile) and add a picture upload to your _Rails Dictionary_ -- show the image on the `show` page for each word/definition.
- [ ] Register for an Amazon AWS account
- [ ] Integrate your AWS S3 account and an S3 bucket into your app
  - [ ] [_DANGER WILL ROBINSON_](https://www.youtube.com/watch?v=OWwOJlOI1nU) -- make super-extra-double-sure you do not commit+push your AWS keys to Github! Contact me before you commit if you are unsure.

**Comment by myk27x** [comment]
pull request -- has merge conflict (possibly resolved) https://github.com/tiy-tpa-ruby-q3-2015/Hours/pull/19

pull request for I18n updates (for recent additions only) https://github.com/tiy-tpa-ruby-q3-2015/Hours/pull/21
