### ISSUE TITLE
Assignment 9-3 - The End of the Tour

### ISSUE THREAD

**Issue by gstark** [myk27x/assignments#34]
What a nine weeks it has been. Just a short time ago we were using the terminal for the first time, learning our way around Atom, running `ruby mycode.rb`, and learning basic syntax.

Now we are on the verge of creating our own apps for the first time! Take a moment to congratulate yourself on how far you have come!
# Last Homework (at least of lecture time)
# Adventure Mode
- Add a post to your blog. Suggested topics: _the idea for my final app_, _reflection on what I've learned_, _what I want to do after The Iron Yard_
- Work on completing issues in the `Hours` repo. Ask Kurtis for an issue, or confirm with him that an issue is available to work on.
# Explorer Mode
- Add ActiveRecord::RecordNotFound handling to either your _Rails Dictionary_ or your _Iron Topics_ app
- Write up some of your user stories and/or make some wireframes for your final app idea.

**Comment by myk27x** [comment]
https://github.com/myk27x/IronTopics

https://medium.com/@myk27x/and-then-there-were-three-3a8d86b29309#.ucapcopm2
