### ISSUE TITLE
Assignment 1-4 - Roshambo

### ISSUE THREAD

**Issue by gstark** [myk27x/assignments#4]
Every Thursday, Jason, Gavin, and Toni go for lunch. In order to determine who pays, a bout of Roshambo (aka rock-paper-scissors) is played. The problem is, programmers are lazy. Jason and Gavin can't possibly be bothered to throw their hands manually. We need you to automate this for us.

See a Roshambo match played: [![RPS FOR THE AGES!](http://img.youtube.com/vi/_eanWnL3FtM/default.jpg)](http://www.youtube.com/watch?v=_eanWnL3FtM)

Use _classes_, _hashes_, _arrays_, _strings_, etc. This assignment will likely use every bit of Ruby we have learned so far to build something greater than the sum of it's parts.
## Explorer Mode
- [x] At the start of each _match_ prompt for the name of the player
  - [x] If no name is given, the program should end
- [x] Play against the computer
  - [x] This means the computer has an "AI" that just throws _randomly_.
- [x] Play one _match_ and show the winner.
  - [x] Each throw is considered an _engagement._
  - [x] The best two of three _engagements_ is a _bout._
  - [x] The best two of three _bouts_ is a _match._
## Adventure mode
- [x] Support playing multiple games (_matches_) of Roshambo.
  - [x] After the match winner is shown:
    - [x] Show a leaderboard.
    - [x] Prompt the player to play again.
## Epic Mode

Choose one of:
- [x] Implement a non-random AI for the computer player based on past throws based on these strategies for [advanced Roshambo AI](https://www.youtube.com/watch?v=rudzYPHuewc)

or
- [x] Keep the leaderboard between sessions
  - [x] When exiting the game, save the leaderboard to a file
    - [x] Extra epic: use a file named `.roshambo` in the user's home directory (like our `.zshrc` config/data files)
  - [x] When starting, if a leaderboard file exists, load it and use that.
## Resources
- Entertain yourself by [reading the rules](http://www.usarps.com/rules/).
- See an unbeatable [Roshambo robot](http://www.theguardian.com/technology/video/2012/jun/27/rock-paper-scissors-robot-video)

**Comment by myk27x** [comment]
Epic mode completed.

https://gist.github.com/myk27x/1fde4b11905f5511ad62

Sorry about the double push... I deleted (or tried to) the 'working.rb' file and everything hated me after that. I was able to fix only to come to find it finally decided to push both 'roshambo.rb' commits... anyway... EPIC! DONE!

**Comment by gstark** [comment]
ok, so it looks like you have two github repos (roshambo and roshambo-1) as well as a gist.

Which is the code you want me to review?

I'd prefer it be in a clear repository in github and a link placed here. If you are still having troubles getting that repo clean, come see me.

**Comment by myk27x** [comment]
Sorry, about the mess on this one.

Roshambo-1 was a fork from Kurtis, which gave me access to his code when other methods weren't working.

https://github.com/myk27x/roshambo should be the proper link to my Roshambo repo.

I sent the gist when I had problems pushing (kept kicking me into vim and couldn't exit, then errors pushing). So I sent the gist as a back-up and 10 mins later both roshambo pushes showed up. _sigh_

**Comment by gstark** [comment]
Woot! Woot! Woot! For completing epic mode, and using classes!

Some feedback:
- instead of

```
    ui_homedir = Dir.home ()
    Dir.chdir (ui_homedir)
    File.exist? ("comp_stats.roshambo")
```

you can do 

```
  path = File.expand_path("~/comp_stats.roshambo")
```

It unusual to change the working directory inside an app unless you _have_ to.
- Love the taunting in the game: "Are you sure?" -- "Are you sure you are sure?" ;)
- I posted a link to a gist where I implemented Roshambo using multiple classes that separate the engagement, bout, match, etc. (link is in Slack)

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/99pXMHBpPgCNW/200w_d.gif)
