### ISSUE TITLE
Assignment 2-1 - HTML/CSS Basics

### ISSUE THREAD

**Issue by gstark** [myk27x/assignments#5]
- [x] Read [this article](http://blog.froont.com/brief-history-of-web-design-for-designers/) on the history of web design.
- [x] Compose a short (a few paragraphs) blog that summarizes your thoughts on the web; where's it's been an where it's going.
- [x] Create an HTML document that contains your blog. It should have a title, a byline and the article itself.
### Explorer Mode
- [x] Mark up your document with valid HTML.
- [x] Use at least 12 different HTML tags.
- [x] Add at least one image to your page.
- [x] Use valid CSS to style the page.
- [x] Research the `id` and `class` HTML attributes.
- [ ] Use at least 12 CSS statements to style the page (a statement includes a selector and a number of properties). Try to use `id` and `class` attributes in your CSS selectors where relevant.
- [x] All of your HTML and CSS should be formatted cleanly and consistently.
### Adventure Mode
- [ ] Use more complex CSS selectors than we covered in class.
- [ ] Use at least 24 CSS statements.
- [x] Use at least one background image (with CSS) somewhere on the page.
### Epic Mode
- [ ] Create a full "Blog" layout for your page (heading, navigation, sidebar, footer, etc.).
## Additional Resources
- https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags
- http://atozcss.com/start-here/
- http://www.evolutionoftheweb.com

**Comment by myk27x** [comment]
https://github.com/myk27x/my_blog

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/YbPdQUzIyJ0t2/200w_d.gif)

**Comment by gstark** [comment]
Looks good!

In general you'll want to name the root page of your site `index.html` so that things like github-pages or other web servers will serve it as the default page.

**Comment by myk27x** [comment]
Got it! (was wondering where/why that came into play!)

Sent from Yahoo Mail on Android
